image: Visual Studio 2022

environment:
  RUST_BACKTRACE: 1

install:
  - powershell -Command "Invoke-WebRequest https://win.rustup.rs/x86_64 -OutFile rustup-init.exe"
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain stable --no-modify-path
  - set PATH=%USERPROFILE%\.cargo\bin;%PATH%
  - cargo --version

build_script:
  - cargo build --release

artifacts:
  - path: target\release\*.exe
