name: Build Rust EXE (MSVC)

on:
  #push:
    #branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust (MSVC)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true

    - name: Build EXE
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: refpack-pipe
        path: target/x86_64-pc-windows-msvc/release/*.exe
