name: Universal macOS Build (Rust)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust targets
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

      - name: Build for x86_64
        run: cargo build --release --target x86_64-apple-darwin

      - name: Build for aarch64
        run: cargo build --release --target aarch64-apple-darwin

      - name: Create universal binary
        run: |
          mkdir -p universal
          lipo -create \
            target/x86_64-apple-darwin/release/your_binary \
            target/aarch64-apple-darwin/release/your_binary \
            -output universal/your_binary

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rust-universal-binary
          path: universal/your_binary
